stages:
  - build

variables:
  IMAGE_SHA_TAG: "evertonagilar/scanlog"

build-image:
  stage: build
  image:
    name: quay.io/buildah/stable:latest
    entrypoint: [""]
  variables:
    BUILDAH_FORMAT: docker
    STORAGE_DRIVER: vfs
  script:
    - buildah bud --layers -t "$IMAGE_SHA_TAG" -f "$CI_PROJECT_DIR/Dockerfile" "$CI_PROJECT_DIR"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
